### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by romansp** [Deffiss/testenvironment-docker#16]
Hi and thanks for the great library! 

I would like to use it in my next project, is it possible to clarify under which license this code is distributed? Would be great to see this added into repository and nuget package. Thanks in advance!

**Comment by Deffiss** [comment]
Hi, you are welcome! It is as free as it is possible :) sorry, I'm not very good at licencing. What would you (and probably most of the people) like to see?

**Comment by romansp** [comment]
@Deffiss, MIT license is preferred most of the time. I believe there's a wizard to scaffold license file directly into repo via GitHub interface. And in csproj it can also be added this way: `<PackageLicenseExpression>MIT</PackageLicenseExpression>`. 

By the way, to avoid packaging info repetition in multiple csproj files, I can recommend adding `Directory.build.props` file.

**Comment by Deffiss** [comment]
I've just added MIT License file and pushed new versions of the packages to nuget so feel free to use on your project.
Thanks for suggestion with `props`, will put it into backlog. Let me know if this issue is resolved from your perspective.

**Comment by romansp** [comment]
@Deffiss awesome! Looks good to me, appreciate quick response. Thank you.
