### ISSUE TITLE
More samples to be provided

### ISSUE THREAD

**Issue by Deffiss** [Deffiss/testenvironment-docker#22]

**Comment by Hellevar** [comment]
From my perspective we need to provide at least two common scenarios:
- .net core api with full integration testing using TestServer and some database
- wpf.core project with usage of Services/DataAccess layers. These layers should be tested by integration tests

**Comment by KirylKiryanchykau** [comment]
+1 to comment above, @Hellevar as far as I can see it both .net core api integration tests and wpf integration tests will look like the same integration tests using TestServer?

Furthermore, we probably could provide next samples:
-  Test environment for AQA end-to-end testing using headless chrome 
-  Some kind of environment for stress testing (either for api or plain MVC project)

**Comment by Hellevar** [comment]
@KirylKiryanchykau not the same, but for .net core api entry point would be http call to test server, but for WPF it would be direct call to some service from business logic, without test server(in wpf it not needed, just interaction between wpf and database)
