### ISSUE TITLE
Generated connection string for SQL Server not working

### ISSUE THREAD

**Issue by mogatti** [Deffiss/testenvironment-docker#39]
Hi,

I tried to use your library and for running mssql containers, using localhost as the Data Source for the connection string does not always work. When I change this to 127.0.0.1 it works. 

This fix for people who cannot get localhost working is also mentioned here https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-troubleshooting-guide

**Comment by Deffiss** [comment]
Hi @mogatti, 
Thanks for reporting that interesting issue. I'll try to reproduce it. We might probably need to change `localhost` to `127.0.0.1` by default. @Hellevar any opinion?

**Comment by mogatti** [comment]
No problem :) I should add this is using Docker Desktop for Windows and running without docker inside docker. I'm not sure exactly why localhost has not worked for me in the past which does not help.

**Comment by Hellevar** [comment]
I didn't experience such issues before

**Comment by mogatti** [comment]
Curious to know what do you get if you try "docker port <container>" on your Linux SQL container?

I'm getting 1433/tcp -> 0.0.0.0:1433
