### ISSUE TITLE
Release a core version?

### ISSUE THREAD

**Issue by johnknoop** [Deffiss/testenvironment-docker#5]
Would it be possible to release a version without dependencies to ElasticSearch and System.Data?

**Comment by Deffiss** [comment]
Hi @johnknoop. ElasticSearch and System.Data are required to add out of the box functionality for MSSQL and Elasticsearch. And yes, this is reasonable. I think at some point I will split the project into two nugets - one for core functionality and another for specific containers like MSSQL or Elasticsearch. Can't commit to any timeframe but if you explain better why you wants only Core functionally maybe I'll repreoritize features list.

**Comment by johnknoop** [comment]
It just seems like unnecessary for me to have those packages, since neither ElasticSearch nor any SQL database are part of my stack. What I like about this library is that it provides a simplified API over DockerDotNet, which I find to be very verbose. I'm currently using DockerDotNet to spin up a MongoDb container to serve as database during automated end-to-end tests.

**Comment by Deffiss** [comment]
Thanks for explaining that. I did some investigation. Looks like it shouldn't be a problem to move container-specific things into a separate nuget with name **TestEnvironment.Docker.Containers**. Most of the work will be in AppVeyor CI/CD. I will close the issue once this will happen.

**Comment by Deffiss** [comment]
#6 is addressing this feature

**Comment by Deffiss** [comment]
Done!

https://www.nuget.org/packages/TestEnvironment.Docker/
https://www.nuget.org/packages/TestEnvironment.Docker.Containers.Elasticsearch/
https://www.nuget.org/packages/TestEnvironment.Docker.Containers.Mssql/
