### ISSUE TITLE
Could not load MySqlConnector assembly due to old version

### ISSUE THREAD

**Issue by hughesappsheet** [Deffiss/testenvironment-docker#50]
We are currently using version 1.3.1 of MySqlConnector in our project (latest is actually 1.3.3). However, TestEnvironment.Docker.Containers.MariaDB is using version 0.61.0. It seems that even with an assembly binding redirect in the app.config, the assembly cannot be loaded. I'm getting this error on environment.Up():

System.IO.FileLoadException: 'Could not load file or assembly 'MySqlConnector, Version=1.3.1.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Perhaps we can upgrade the nuget reference for MySqlConnector in TestEnvironment to the latest version?

**Comment by Deffiss** [comment]
Hi, v1.1.0 nuget is available.

**Comment by hughesappsheet** [comment]
Thank you!
