### ISSUE TITLE
Fix name of Kafka part

### ISSUE THREAD

**Issue by a-z-hub** [Deffiss/testenvironment-docker#63]
Invalid name Kafka project:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/4180472/158563811-3cc08ecd-6a0f-48d1-bec5-07b0aaeb2ede.png">
TestEnvironmen_b_t.Docker.Containers.Kafka -> TestEnvironment.Docker.Containers.Kafka

Change:
- the name of the directory
- project name
- search other issues in the names

**Comment by Deffiss** [comment]
Thanks, @a-z-hub , merged!
