### ISSUE TITLE
Docker.DotNet package requires update to latest version

### ISSUE THREAD

**Issue by Lukino** [Deffiss/testenvironment-docker#69]
When I update Docker.DotNet 3.125.12, testenvironment-docker started to thow exception, because DockerClientConfiguration constructors.
Here is change log https://github.com/dotnet/Docker.DotNet/compare/v3.125.5...v3.125.12#diff-a944f48314882e7cae293af14f782fdae674e6af5e12fc2f0abeb705cd3c17b7R19

**Comment by Lukino** [comment]
#70 Pull request

**Comment by Deffiss** [comment]
Hi, @Lukino
Thanks for reporting the issue. Let me review your PR.

**Comment by Deffiss** [comment]
Could you please clarify about the reason of upgrading the library? Is it for keeping it up to date or there is a desired functionality in a latest version?

**Comment by Lukino** [comment]
It causes constructor error during tests run.
`  Message: 
System.MissingMethodException : Method not found: 'Void Docker.DotNet.DockerClientConfiguration..ctor(System.Uri, Docker.DotNet.Credentials, System.TimeSpan)'.

  Stack Trace: 
DockerClientExtentions.CreateDefaultDockerClient()
DockerEnvironmentBuilder.ctor(ILogger logger)
IntegrationFixture.PrepareDockerEnvironment(Boolean useContainerIpAddresses, SqlContainerSettings settings) line 127
IntegrationFixture.InitializeAsync() line 68`

**Comment by Lukino** [comment]
@Deffiss Do you have any estimation for new release ?

**Comment by Deffiss** [comment]
@Lukino - just released, please wait for few minutes until it become available.

**Comment by Deffiss** [comment]
I am going to close this issue. Please, let me know if it is not fixed yet for some reasons.

**Comment by Lukino** [comment]
Yep, new version works fine.
Thanks
