### ISSUE TITLE
Use in Jenkins

### ISSUE THREAD

**Issue by LGmatrix13** [Deffiss/testenvironment-docker#79]
Would it be possible to use this package in a Jenkins pipeline? As far as I know, Jenkins uses docker. Would this be a docker in docker situation? Or would it be more simple?

**Comment by Deffiss** [comment]
Hi @LGmatrix13 
If you have docker in docker environment then yes, its possible. See **DockerInDocker** option:
 https://github.com/Deffiss/testenvironment-docker/blob/3d3c590fde4894eda2db0371ca5c4a2880f0f920/src/TestEnvironment.Docker/IDockerEnvironmentBuilder.cs#L14

**Comment by Deffiss** [comment]
Hi @LGmatrix13 
My understanding is that your Jenkins pipeline may run particular steps inside Docker containers. In this case, yes, you'll have a situation of Docker in Docker and you'll have to take that into account when build your tests.
